apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-kubernetes-hello-kubernetes
  labels:
    app.kubernetes.io/name: hello-kubernetes
    app.kubernetes.io/instance: hello-kubernetes
    app.kubernetes.io/version: "1.10"