#ENC[AES256_GCM,data:fvxsM/RBCcDTq4AxL4IIfSPVYKKWrD+Jrw==,iv:VJXcgeX1sY+8s6KhvO3txCOwe6PJpUtHRSZvDcy0pbA=,tag:XS8D0FhraMzhYQHabgZzSA==,type:comment]
message: ENC[AES256_GCM,data:qRNJaNLAeQ==,iv:0B2tLDLWaDqG2oIxkP2/0bi+qdl26YTWI15dLVtoIOA=,tag:fgd6IdkjkSZML7DtgThfog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-08-03T11:57:40Z"
    mac: ENC[AES256_GCM,data:R7A1rm7JKjTOcq4vn2nus0gw4aCyGOSvTelH8frKYYZ6NgohFrvVW7CYjX49IAndUl8FIeb6dRL1rC/cJ4850/GgCbNs0S5yjPsSGTibfPYwOgEJlZlDNcsQHtYy48zBtyn0x3Dr/HizX/QVbZgiCZh02utX5bkFsOaLBpH93b0=,iv:LYjWwvj7zMN0jj6EMkXrceD7FADCU0dNs/enlZr9IA4=,tag:jnGdyuKh3jOwNGtiYjE2yw==,type:str]
    pgp:
        - created_at: "2023-08-03T11:57:22Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA0C69WmD7uXdAQv7B9eUtzWhkqfH8Xopa1nyBD7HYRbIfDsUyagvGflGT7R2
            2DFkeslTokcq58ZTKoim1q+oSnmKGNIXFSKeIDERc1yXe5MRejeD3NGGj3ic+CXn
            7JjhcbiawXOH7Ac5Vc1Chcs8oFkivp5V0pN2vaDqO1Hu10snZAQGHOpxvBqF7XwP
            4Hd++99H7jTYgzBbEr5jWT/CDG+CGJ55W25OzILMRxReLPtYtXkBI3of+BX1ucGN
            5B7vD6JKfT5K54gEd/we3ygUB9XKMLpz/hYbuUoeraPI4Mg8Q4TJG4neLze+0o+e
            sOaixYd752DytdmJnq0Kj17QA0d9/DrJLhmlx7WmPxewcSc2ksNTdKr08hpGASlk
            7y25w0IGbw4FMxNTbhYOqsBaqLpHNHWSGJU99CV+4q021iPZmJeQXe+ua+4lJ9hD
            LiZ926r/yEQmoJ2VTvCBpCq3vpcquBo4CtWDyf2k8/EEivxzQxU0wHJvQtCRELhJ
            hR1EGx5SlN01D5dPbnEG0l4BplojPgDuwGjNOI8adXIymSXpBk/2zlkXRhEg0dDY
            wsCBdlpXNX+9iOLXevEsxrJsJUTeBdZPkXu1Sa9i9X8JNf05d2o2IPq/fB6MoQNU
            H5wFNwvkX+vvezckL1bz
            =8OkV
            -----END PGP MESSAGE-----
          fp: A3BA8A295ED00D44C2B4A58A451B80B99524F241
        - created_at: "2023-08-03T11:57:22Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA+NFoivjcKA8AQwAz8sCA3aJnHNDoYa9X/yrXrZa4Q1Hg/oEDqfCjLcp6BmT
            conNcsKgNABzM/jsSYBYJM95UU06Y7NG/N1m6O3VqAhUJnY9K5UFiZf2/aU6nfVC
            eNarVPKE1ldh8jHEl7DzVS4NGakJNS2Da3GKo2X3ine3sLWK/TIaCTAolCPc9X1m
            rq3vRmVoSiIw/j6bRnYOxExYmY47XFDFNDXNMXvi6uKPk8rw3hNH/B0NdTpAk7Fw
            KxREW6MX1lstqvh77g/884LSKJ4GIQBwXzV4wKgSpuvN7oVjphDhk9r/lE3ovJ2o
            Sc3fN5r5vW3908zAECAzQy2NWqG/jWx/LPxmaP+CvxmDpemMSSmbs9aOo1bWodKx
            Xa3YBJzE/cY7vVH8Effi57SIY3EveZvkCoV0OwqDcdEpgbXJuxLheBNL1YgXkvH/
            FA3j36TZIeK2uPnsCxfSHO4ilX77TgpaxrqxOv3vDI+9Brt7934sPNIUtmqDQnZ+
            V5VAW4TdX86ABDJ9p/fM0l4BauMcgjtTuyH0k1LiX8iV1AT19bTMWBbHAQEGRGiC
            1lAtpabZybPCOOetnqYmTFSdk5c2FSEmYd3fZ4iZx5FVHnjYH0IyiBgXojrtBnUY
            7i9JIAyq5zSOSACJQxLb
            =azI1
            -----END PGP MESSAGE-----
          fp: EBB9CFD6A70178031C35691BE037DB81E17685DA
    unencrypted_suffix: _unencrypted
    version: 3.7.3
